### ISSUE TITLE
Cookie header is missing from request headers

### ISSUE THREAD

**Issue by philippemiguet** [prisma-labs/graphql-playground#1119]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [x] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
macOS Catalina version 10.15.2 (19C57)

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
Desktop app version 1.8.10 (1.8.10.5129) 

#### What is the expected behavior?
When setting a header `cookie: foo=bar` I expect that header to be sent so I can get the cookie in my express app.

#### What is the actual behavior?
I'm specifying a `cookie: foo=bar` header but `req.cookies` is empty. If I copy curl command, I do see the header being specified in the curl command, and upon executing it in my terminal `req.cookies` is populated. That's why I think the playground app may not be sending the cookie header. 

Other headers seems to work, because if I send the `authorization: Bearer bar` header, `req.authorization` will contain the `Bearer bar` value.

#### What steps may we take to reproduce the behavior?
1. Open desktop app
2. Write a GraphQL query
3. Add header 
```
{
	"cookie": "foo=bar"
}
```
4. Add logs in your app to verify content of `req.cookies`
5. Play the query

Alternative
1. Open playground at your GraphQL URL
2. Write a GraphQL query
3. Add header 
```
{
	"cookie": "foo=bar"
}
```
4. Play query
5. Inspect request headers from network tab in your browser
6. cookie header is missing

**Let me know if you need more information or if I'm missing something obvious :)**
_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by anault** [comment]
@philippemiguet In the playground settings, try setting `request.credentials` to `include` as suggested here: https://github.com/prisma-labs/graphql-playground/issues/1073#issuecomment-526509499
