### ISSUE TITLE
SaveSettings handler broken in version 1.7.21 

### ISSUE THREAD

**Issue by elektro1103** [prisma-labs/graphql-playground#1197]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ x] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
MacOS Catalina

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.7.21

#### What is the expected behavior?
saveSettings handler should allow for settings to be saved... 

#### What is the actual behavior?
SaveSettings handler should fire correctly and save my settings...

#### What steps may we take to reproduce the behavior?
install latest package, launch playground,  open dev tools, go to settings, change any settings press command+s or click saveSettings button . saveSettings handler is not a function. 
If i hard code in version 1.7.9 (first version i tested) into the script tag inside the render-playground-page.js file the error is resolved. 

_Please provide a gif or image of the issue for a quicker response/fix._
![Screen Shot 2020-04-10 at 10 40 41 PM](https://user-images.githubusercontent.com/50589244/79033461-c381c400-7b6b-11ea-8b27-6a1431722e93.png)

**Comment by acao** [comment]
@beeman is this something we forgot to test in the last release? Hmmm

**Comment by acao** [comment]
![image](https://user-images.githubusercontent.com/1368727/79051569-e8734700-7bfe-11ea-8926-6621dfbf6d4b.png)

confirmed on netlify

**Comment by acao** [comment]
In fact, I can't seem to find when this was last set up properly in master. looks like this prop handler has been missing for a while, looking at `PlaygroundWrapper.tsx` more closely

**Comment by elektro1103** [comment]
Thanks guys !! appreciate the quick fix!
