### ISSUE TITLE
GQL-Playground: Schema tab crashes but doc works

### ISSUE THREAD

**Issue by udaykor** [prisma-labs/graphql-playground#1248]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [x] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Mac OS X Catalina

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.16.12

#### What is the expected behavior?
My schema is valid, I can query & mutate. I can look at docs. However when I select the schema tab, the browser reloads to a blank page. I have introspection set to true. 

#### What is the actual behavior?
I should be able to look at the schema from GQL Playground

#### What steps may we take to reproduce the behavior?
I am using these to get to the GQL Playground
    "graphql-tag": "^2.10.3",
    "graphql-yoga": "^1.18.3",

_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by jeggy** [comment]
This also happens for me. For some reason it seems like all lines that should be `type *typename* {`are just missing.

![image](https://user-images.githubusercontent.com/51459/86189120-8c9ec700-bb38-11ea-9557-8f2ef5ace0d4.png)

![Screenshot from 2020-07-01 01-15-24](https://user-images.githubusercontent.com/51459/86189089-742eac80-bb38-11ea-867d-ea3cebd31be2.png)

**Comment by adudhe-womply** [comment]
Observing same issue.
I have referred the static html with CDN resources https://github.com/prisma-labs/graphql-playground/blob/master/packages/graphql-playground-html/minimal.html

**Comment by ajeydudhe** [comment]
I am also observing same issue.
Had referred https://github.com/prisma-labs/graphql-playground/blob/master/packages/graphql-playground-html/minimal.html

**Comment by Stradivario** [comment]
I am here just to reference the same issue

https://github.com/prisma-labs/graphql-playground/issues/1252

**Comment by chaffeqa** [comment]
FYI i think https://github.com/prisma-labs/graphql-playground/pull/1245 fixes this

**Comment by leonbe02** [comment]
Any ETA on when this fix will be deployed?

**Comment by udaykor** [comment]
I found using Apollo-Server-Express to solve this. Now more graphql-yoga for me!

**Comment by acao** [comment]
dupe, fixed in last release
