### ISSUE TITLE
GraphQL Playground "Schema" tab crash, but "docs" tab works fine

### ISSUE THREAD

**Issue by thibault60000** [prisma-labs/graphql-playground#1252]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ X] GraphQL Playground HTML
- [X ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Windows 10

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
    "prisma-binding": "1.5.19"
    "prisma": "^1.34.10"

#### What is the expected behavior?
I would like to use the "schema" tab of my playground

#### What is the actual behavior?
When I start my Playground : 
- Docs tab work
- Schema tab doesn't work : crash page

#### What steps may we take to reproduce the behavior?

datamodel.prisma or datamodel.graphql...
```
type Post {
  id: ID! @id
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
  isPublished: Boolean! @default(value: false)
  title: String!
  image: String!
  greatImage: String!
  text: String!
  author: User!
  category: PostCategory
}

type User {
  id: ID! @id
  email: String! @unique
  password: String!
  name: String!
  rules: [String!]! @scalarList(strategy: RELATION)
  posts: [Post!]!
}

type PostCategory {
  id: ID! @id
  label: String!
}
```
Index.js GraphQL Server

```
const server = new GraphQLServer({
  typeDefs: "src/schema.graphql",
  resolvers,
  context: req => ({
    ...req,
    db: new Prisma({
      typeDefs: "src/generated/prisma.graphql",
      endpoint: process.env.PRISMA_ENDPOINT, 
      secret: process.env.PRISMA_SECRET, 
      debug: true 
    })
  })
});

// Démarre le serveur
server.start(() => console.log("Server is running on http://localhost:4000"));
```

Command :
    `"start": "nodemon -e js,graphql -x node -r dotenv/config src/index.js",`

_Please provide a gif or image of the issue for a quicker response/fix._

![2020-07-07_22h37_52](https://user-images.githubusercontent.com/18366294/86840034-8366aa80-c0a2-11ea-854d-5ee460c66dcf.png)

![2020-07-07_22h38_18](https://user-images.githubusercontent.com/18366294/86840081-97aaa780-c0a2-11ea-8869-91ef6ccc02d3.png)

It's the "Schema" tab

Thanks you !

**Comment by acao** [comment]
fixed in last release
