### ISSUE TITLE
Regresion introduced in render-playground-page.ts (Couldn't find the requested file from CDN)

### ISSUE THREAD

**Issue by Stradivario** [prisma-labs/graphql-playground#1254]
There is a pull request https://github.com/prisma-labs/graphql-playground/security/advisories/GHSA-4852-vrh7-28rf Reflected (XSS in GraphQL Playground React, HTML and Middlewares)

Inside of this pull request we have `buildCDNUrl` function which is combining the url for specific version
https://github.com/prisma-labs/graphql-playground/blob/63eef0b7a0873e996c4cffc90ed4a99bc6ee39e7/packages/graphql-playground-html/src/render-playground-page.ts#L92

```ts
const buildCDNUrl = (packageName: string, suffix: string) => filter(`${cdnUrl}/${packageName}/${version ? `@${version}/` : ''}${suffix}` || '')
```

When i am using the last version `patch` of `graphql-playground-html` i get response from the browser saying 

https://cdn.jsdelivr.net/npm/graphql-playground-react/@1.7.1/build/static/css/index.css
```
Couldn't find the requested file /@1.7.1/build/static/css/index.css in graphql-playground-react.
```

Also the same situation is for `js` bundle

https://cdn.jsdelivr.net/npm/graphql-playground-react/@1.7.1/build/static/js/middleware.js
```
Couldn't find the requested file /@1.7.1/build/static/js/middleware.js in graphql-playground-react.
```

What i have found out is that `buildCDNUrl` function has one `slash` more at the url so instead of 

```ts
filter(`${cdnUrl}/${packageName}/${version ? `@${version}/` : ''}${suffix}` || '')
```

We should have

```ts
filter(`${cdnUrl}/${packageName}${version ? `@${version}/` : ''}${suffix}` || '')
```

Maybe it is hard to notice but between ${packageName} and ${version...} we have `/` which is not correct `url`

Correct URL:

```
https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.1/build/static/css/index.css
```

Incorrect URL:

```
https://cdn.jsdelivr.net/npm/graphql-playground-react/@1.7.1/build/static/css/index.css
```

I will create PR for this change so we can use our favorite Editor again with latest changes :))) 

Regards,
Kristiyan Tachev (@Stradivario)

**Comment by acao** [comment]
fixed in latest release
