### ISSUE TITLE
[graphql-playground-html] Yarn package missing version 1.6.26

### ISSUE THREAD

**Issue by Huljo** [prisma-labs/graphql-playground#1260]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [X] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Debian Bullseye

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.6.26

#### What is the expected behavior?
Being able to yarn the package

#### What is the actual behavior?
yarn add apollo-server-express
````
error An unexpected error occurred: "https://registry.yarnpkg.com/@apollographql/graphql-playground-html/-/graphql-playground-html-1.6.26.tgz: Request failed \"404 Not Found\"".
````

#### What steps may we take to reproduce the behavior?
yarn add apollo-server-express

`apollo-server-express` use version 1.6.26 
https://github.com/apollographql/apollo-server/blob/main/packages/apollo-server-express/package.json#L30

But the package is not found in the yarn registry:
https://registry.yarnpkg.com/@apollographql/graphql-playground-html/-/graphql-playground-html-1.6.26.tgz

**Comment by devop911** [comment]
This seems to be a problem with npm package registry,
got many errors on all build pipleline:

npm ERR! 404 Not Found - GET https://registry.npmjs.org/@hapi/formula/-/formula-2.0.0.tgz

**Comment by Huljo** [comment]
Problem solved, the package is available again.
