### ISSUE TITLE
[Question] How does playground manage to print the SDL ordered semantically instead of alphabetically. (i.e Query type first, then types referred from that and so on..)

### ISSUE THREAD

**Issue by Ambro17** [prisma-labs/graphql-playground#1266]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [x] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
N/A

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
Not an issue

#### What is the expected behavior?
N/A

#### What is the actual behavior?
N/A

#### What steps may we take to reproduce the behavior?
Open playground
Click on schema
See that Query type is first, then the types referred there, and so on. The order is not alphabetical

_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by acao** [comment]
[`printSchema()` in `graphql-js`](https://github.com/graphql/graphql-js/blob/bbd8429b85594d9ee8cc632436e2d0f900d703ef/src/utilities/printSchema.js) determines this!

in the latest release, i removed any additional formatting, as graphql 15 does a fine job of formatting the printed output
