### ISSUE TITLE
Is there a way to generate URL query parameters to pass query/headers/variables instead of graphqlbin.com link?

### ISSUE THREAD

**Issue by bellierjonathan** [prisma-labs/graphql-playground#1267]
## This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [X] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

On the web side is there a way to generate URL with HTTP query parameters (query/headers/variables)?

I tried to force URL parameters and it works but when I run a new query the URL isn't generated?

_graphql/explorer_?**query=XXXXX**&**variables=XXXXX**

Thanks

**Comment by acao** [comment]
yes you can do that, but i couldn’t find out how to supply the url as well. you can supply ?query=&variables= and it worked for me
