### ISSUE TITLE
Cannot load Apollo Playground (browser) due to "Content Security Policy directive" – error while loading middleware.js from cdn.jsdelivr.net

### ISSUE THREAD

**Issue by slavovojacek** [prisma-labs/graphql-playground#1269]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [x] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

Most likely all OS's

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

Most likely all versions that depend on https://cdn.jsdelivr.net/npm/@apollographql/graphql-playground-react@1.7.32/build/static/js/middleware.js

#### What is the expected behavior?

Load Apollo Playground

#### What is the actual behavior?

Apollo Playground does not load

#### What steps may we take to reproduce the behavior?

Try to access any Apollo Playground

_Please provide a gif or image of the issue for a quicker response/fix._

<img width="1792" alt="Screenshot 2020-08-30 at 11 30 03" src="https://user-images.githubusercontent.com/4658565/91656869-2c82bd80-eab4-11ea-812e-db3336617a7b.png">

**Comment by acao** [comment]
you are using a fork of this repository. youll need to file the issue at apollographql/graphql-playground
