### ISSUE TITLE
[Proposal] Explorer

### ISSUE THREAD

**Issue by robinweser** [prisma-labs/graphql-playground#936]
Over at [OneGraph](https://github.com/OneGraph) we've built and just recently open sourced an Explorer plugin for GraphiQL: https://github.com/OneGraph/graphiql-explorer.

> Check out the [introduction blog post](https://www.onegraph.com/blog/2019/01/24/How_OneGraph_onboards_users_new_to_GraphQL.html) to learn why and how we built it and how it works.

After talking to @schickling, I would love to see adding it to the Playground as well, as [more and more people](https://github.com/OneGraph/graphiql-explorer/issues/3) are using it instead of GraphiQL. Porting should be fairly simple, but I might need some help with the styling.

I will add a PR that adds the explorer as is soon.
Some guidance and feedback would then be super useful. (cc @Huvik)

-----

Probably not related to this issue itself:

> **Note**: I did not check the source code yet, so if there already is something like that - forget about it.

Maybe we should think about some kind of plugin system? Seeing #935 and having some more stuff coming up soon, it might be useful to have a simple way to add those.
Might be enough to register a menu button that toggles a panel which is passed all the available data.

**Comment by Huvik** [comment]
Hey @rofrischmann that looks fantastic! I can see explorer be part of documentation drawer on right side. 

If you need any guidance you can check the latest addition of SDL view #897 or ping me here or twitter. Regarding feedback, it should somehow reflect whole playground UI and styling to fit the whole theme of the playground.

Plugins are a bigger topic, I have a working draft for plugin architecture, but I need to finish it. There are few issues addressing it #235  #648. And yea one of plugins proposed in my draft is a sidebar plugin what is adding panes to documentation.

**Comment by Nishchit14** [comment]
Interesting!!  @rofrischmann you guys did a fantastic job by creating `Explorer`

I'm wondering if I can help to implement in GraphQL-Playground. would happy to contribute.

Here, I'm building a web playground for GraphQL using OneGraph's [Explorer](https://github.com/OneGraph/graphiql-explorer.) and APIs.guru's [Voyager](https://github.com/APIs-guru/graphql-voyager).

Demo is here https://fireql.dev/?url=https://api.spacex.land/graphql

![image](https://user-images.githubusercontent.com/5078921/56467630-120bef00-643f-11e9-9179-c8135b60bbdb.png)

**Comment by ConProgramming** [comment]
Is this going anywhere?

**Comment by sahilrajput03** [comment]
Whats the status of this issue???

**Comment by acao** [comment]
this repo will soon be archived as per the announcement earlier this year! no new features unfortunately. someone should fork it!

**Comment by wtrocki** [comment]
I would recomend to take look into upcoming https://github.com/graphql/graphiql
It is going to have a lots of features. Any suggestions can be logged there.
