### ISSUE TITLE
Schema polling feches new schema, does not update the UI

### ISSUE THREAD

**Issue by grahamb** [prisma-labs/graphql-playground#965]
Schema polling does not update the UI when new fields are added.

#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [x] GraphQL Playground

#### What OS and OS version are you experiencing the issue(s) on?

macOS Mojave 10.14.2

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

1.8.9

![screenshot 2019-02-11 10 47 10](https://user-images.githubusercontent.com/146111/52585933-02db4600-2deb-11e9-9622-245bf550731b.png)

#### What is the expected behavior?

When a field does not exist in the schema, but is present in a query, Playground correctly marks it as an error with a red underline and associated tooltip. When the field is added to the schema and Playground updates in the background, the field should no longer be marked as an error.

#### What is the actual behavior?

The field is still marked as an error, despite it being present in the IntrospectionQuery result.

![graphql](https://user-images.githubusercontent.com/146111/52586918-901f9a00-2ded-11e9-8a01-78fed2b9869e.gif)

(Better quality YouTube version: https://www.youtube.com/watch?v=SbaODtcOh-E)

**Comment by Huvik** [comment]
Thanks for reporting that, looks like there is a problem with updating schema inside codemirror. I will try to address this bug this week.

**Comment by swashata** [comment]
Hello,

I can confirm that this happens on the `SCHEMA` and `DOC` sidebar too. When polling is enabled and I add something new to schema, it doesn't update the `SCHEMA` or `DOC` sidebar.

**Comment by nijat13** [comment]
Yeah, guys. Is there any update?

In case when restart the playground it works well...

**Comment by WilliamDugdale** [comment]
I'm having similar problems with the electron app on linux ubuntu. However, for me, sometimes it works, so I suppose the bug is technically intermittent! (Allthough I would say it's broken in about 90% of instances.) Perhaps this will help with debugging.
When it does work, it usually remains working until 'something unsual' happens, which in my case is usually an internal error owing to poorly formed schema being sent...

**Comment by dsanders11** [comment]
@Huvik, any update? It's rather painful to have this feature broken, as it requires restarting GraphQL Playground to get an updated schema.

Further info: Running the Electron version, tested both 1.8.8 and 1.8.10, both are broken. I tested 1.8.8 in case a220dc00b7bb0fa3c35f13b8691c66be8ef49a82 was the commit that broke things, but it doesn't look like it. Using the developer tools, I'm not seeing the automatic schema polling happening. If I manually refresh the schema, I see the POST request go out and get a response, but nothing updates. It's not just the CodeMirror part, the schema pane also stays showing the old schema. Basically, nothing related to schema updating is working.

**Comment by galvesribeiro** [comment]
+1

Same issue here on the OSX app.

**Comment by bangarangler** [comment]
Any updated on this? Same issue on macos with the app

**Comment by anthonysapien** [comment]
I'm having the same issue on MacOS with the app. I have to restart the app for the UI to update.

**Comment by DonCook** [comment]
Same on Windows.

**Comment by nhuesmann** [comment]
I hate to +1 GH issues, but since this hasn't gotten much attention for a while I'll add my +1.

Mac OS 10.14.6
GraphQL Playground - 1.8.10 (1.8.10.5129)

**Comment by thu-san** [comment]
+ 1 here too

**Comment by ivbsoftware** [comment]
Same here

**Comment by firstaml-dima** [comment]
Same here

**Comment by jeanlescure** [comment]
I have the same error

Mac OS 10.15.1
GraphQL Playground 1.8.10 (1.8.10.5129)

**Comment by hong823** [comment]
+1

Same issue here on Mac OS app, it worked fine after the restart of the app.

Mac OS 10.14.6
GraphQL Playground 1.8.10 (1.8.10.5129)

**Comment by eyalw** [comment]
still not working :(

**Comment by hybridmuse** [comment]
This is abandonware.

**Comment by AHBruns** [comment]
Still having this error. Would downgrading to an older version fix this in the meantime?

**Comment by galvesribeiro** [comment]
> This is abandonware.

Yeah, I think the same.

Dropped and started using Altair. The maintainers are very keen to help and the thing works like a charm.

**Comment by nhuesmann** [comment]
@galvesribeiro Thanks for the rec on Altair, looks like a promising alternative!
